routes/web.php
<?php

/****************************************
 * 商城前台路由组
 ****************************************/
Route::middleware('user.cars')->group(function () {

    Route::get('/', 'HomeController@index');

    // 1. 通过商品拼音首字母得到商品列表
    // 2. 搜索商品
    Route::get('products/pinyin/{pinyin}', 'ProductController@getProductsByPinyin');
    Route::get('products/search', 'ProductController@search');

    // 1. 商品分类的资源路由，
    // 2. 商品的资源路由哦
    // 3. 购物车的资源路由
    Route::resource('categories', 'CategoryController')->only('index', 'show');
    Route::resource('products', 'ProductController')->only('index', 'show');
    Route::resource('cars', 'CarController');

    // 优惠券兑换模板
    Route::get('coupon_templates', 'CouponTemplateController@index');
    // 领取优惠券
    Route::post('coupons', 'CouponController@store');

    // 秒杀商品
    Route::get('seckills/{id}', 'User\SeckillController@show');
    // 获取已经秒杀的人名
    Route::get('seckills/{id}/users', 'User\SeckillController@getSeckillUsers');
});

/****************************************
 * 用户相关的路由
 ****************************************/
Route::middleware('user.auth')->prefix('user')->namespace('User')->group(function(){

    /****************************************
     * 1. 用户的个人中心
     * 2. 订阅星期一商城以获取新闻
     ****************************************/
    Route::get('/', 'UserController@index');
    Route::put('subscribe', 'UserController@subscribe');

    /****************************************
     * 1. 修改密码页面
     * 2. 修改密码
     ****************************************/
    Route::get('password', 'UserController@showPasswordForm');
    Route::post('password', 'UserController@updatePassword');

    /****************************************
     * 1. 用户设置个人中心
     * 2. 修改用户头像
     * 3. 修改用户资料
     ****************************************/
    Route::get('setting', 'UserController@setting');
    Route::post('upload/avatar', 'UserController@uploadAvatar');
    Route::put('update', 'UserController@update');

    /****************************************
     * 1. 设置用户的默认收货地址
     * 2. 根据省份 id 获取城市列表
     * 3. 收货地址的资源路由
     ****************************************/
    Route::post('addresses/default/{address}', 'AddressController@setDefaultAddress');
    Route::get('addresses/cities', 'AddressController@getCities');
    Route::resource('addresses', 'AddressController');

    /****************************************
     * 1. 用户收藏商品的列表
     * 2. 收藏，取消收藏商品
     * 3. 订单的资源路由
     ****************************************/
    Route::get('likes', 'LikesController@index');
    Route::put('likes/{id}', 'LikesController@toggle');
    Route::resource('orders', 'OrderController')->only('index', 'show', 'destroy');

    // 确认收货
    Route::patch('orders/{order}/shipped', 'OrderController@confirmShip');
    // 完成订单+评价
    Route::post('orders/{order}/complete', 'OrderController@completeOrder');
    // 取消订单
    Route::get('orders/{order}/cancel', 'OrderController@cancelOrder');

    // 用户的积分
    Route::get('scores', 'UserController@indexScores');
    // 用户拥有的优惠券
    Route::get('coupons', 'UserCouponController@index');
    // 使用兑换码兑换优惠券
    Route::get('coupon_codes', 'UserCouponController@exchangeCoupon');


    // 用户通知的所有接口
    Route::get('notifications', 'NotificationController@index');
    // 标位已读
    Route::get('notifications/{id}/read', 'NotificationController@read');
    // 已读所有
    Route::get('notifications/read_all', 'NotificationController@readAll');
    // 查看通知详情
    Route::get('notifications/{id}', 'NotificationController@show');
    // 轮询未读消息总数
    Route::get('un_read_count/notifications', 'NotificationController@getUnreadCount');

    /****************************************
     * 1. 订单的创建（包括直接下单和购物车下单
     * 2. 退款接口
     * 3. 忘记付款了，再次付款
     ****************************************/
    // 统一创建订单
    Route::get('comment/orders/create', 'StoreOrderController@create');
    Route::post('comment/orders', 'StoreOrderController@store');

    // 退款和支付
    Route::post('pay/orders/{order}/refund', 'RefundController@store');
    Route::get('pay/orders/{order}/again', 'PaymentController@againStore');

    // 秒杀的订单创建接口
    Route::post('seckills/{id}', 'SeckillController@storeSeckill');
});


/****************************************
 * 互联登录的路由，包括 github, QQ， 微博 登录
 ****************************************/
Auth::routes();

Route::namespace('Auth')->group(function(){

    // 获取验证码
    Route::get('captcha', 'RegisterController@captcha');

    /****************************************
     * 1. 激活账号的路由
     * 2. 重新发送激活链接的路由
     ****************************************/
    Route::get('register/active/{token}', 'UserController@activeAccount');
    // again send active link
    Route::get('register/again/send/{id}', 'UserController@sendActiveMail');

    /****************************************
     * 互联登录的路由，包括 github, QQ， 微博 登录
     ****************************************/
    Route::get('auth/oauth/{type}', 'AuthLoginController@redirectToAuth');
    Route::get('auth/oauth/callback/{type}', 'AuthLoginController@handleCallback');
    Route::get('/auth/oauth/unbind/{type}', 'AuthLoginController@unBind');
});

// 支付通知的接口
Route::get('pay/return', 'PaymentNotificationController@payReturn')->middleware('user.cars');
Route::post('pay/notify', 'PaymentNotificationController@payNotify');

// 取消订阅邮件
Route::get('unsubscribe/{email}', 'HomeController@unSubscribe')->name('site.email');

app/Http/Controllers/Api/V1/ProductController.php
<?php

namespace App\Http\Controllers\Api\V1;

use App\Http\Resources\ProductResource;
use App\Models\Product;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Cache;

class ProductController extends Controller
{
    public function show($uuid)
    {
        $product = Product::query()->where('uuid', $uuid)->firstOrFail();
        $product->load('detail');

        // 直接使用缓存
        $today = Carbon::today()->toDateString();
        Cache::increment($product->getViewCountKey($today));

        return responseJson(200, 'success', new ProductResource($product));
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Node;
use App\Models\Product;
use App\Models\ProductPinYin;
use App\Models\User;
use App\Services\ScoreLogServe;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Cache;

class ProductController extends Controller
{

    /**
     * 商品列表
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        // 随机查出一些商品展示
        $products = Product::query()->inRandomOrder()->take(9)->get(['uuid', 'name'])->split(3);
        $pinyins = ProductPinYin::query()->orderBy('pinyin')->pluck('pinyin');

        return view('products.index', compact('products', 'pinyins'));
    }


    /**
     * ajax 通过商品首字母查询商品
     * @param $pinyin
     * @return mixed
     */
    public function getProductsByPinyin($pinyin)
    {
        $products = Product::query()->where('first_pinyin', $pinyin)->get(['id', 'name'])->split(3);

        return $products;
    }


    /**
     * 商品搜索
     *
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function search(Request $request)
    {
        $keyword = $request->input('keyword', '');
        $page = abs((int)$request->get('page', 1));
        $limit = (int)$request->get('limit', 20);
        $offset = (int) ($page - 1) * $limit;
        
        // 全文索引
        try {
    
            $parameters = [
                'multi_match' => [
                    'query' => $keyword,
                    'fields' => ['title', 'body'],
                ]
            ];
            
            $count = Product::searchCount($parameters);
            $searchCount = $count['count'] ?? 0;
            $searchResult = Product::search($parameters, $limit, $offset);
            $filterIds = Collection::make($searchResult['hits']['hits'] ?? [])->pluck('_source.id');
            $models = Product::query()->findMany($filterIds);
    
            $products = new LengthAwarePaginator($models, $searchCount, $limit, $page);
            
        } catch (\Exception $e) {
    
            $products = Product::query()->withCount('users')->where('name', 'like', "%{$keyword}%")->paginate($limit);
        }

        return view('products.search', compact('products'));
    }

    /**
     * 单个商品显示
     *
     * @param                 $uuid
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show($uuid)
    {
        /**
         * @var $user User|null
         */
        $product = Product::query()->where('uuid', $uuid)->firstOrFail();


        if (! $product->today_has_view) {
            $product->today_has_view = true;
            $product->save();
        }
        // 直接使用缓存
        $today = Carbon::today()->toDateString();
        Cache::increment($product->getViewCountKey($today));


        // 商品浏览次数 + 1
        $user = auth()->user();

        // 同类商品推荐
        $recommendProducts = Product::query()
                                    ->where('category_id', $product->category_id)
                                    ->take(5)
                                    ->get();

        // 加载出详情，收藏的人数, 评论
        $product->load([
            'detail',
            'users',
            'comments' => function ($query) {
                $query->latest();
            },
            'comments.user'
        ]);
        $product->userIsLike = $product->users()->where('id', auth()->id())->exists();

        // 如果登录返回所有地址列表，如果没有，则返回一个空集合
        if ($user) {

            // 浏览商品增加积分
            (new ScoreLogServe)->visitedProductAddScore($user, $product);
        }

        return view('products.show', compact('product', 'recommendProducts'));
    }

    /**
     * @return \Illuminate\Contracts\Auth\StatefulGuard
     */
    protected function guard()
    {
        return auth()->guard();
    }
}

resources/views/products/index.blade.php
@extends('layouts.shop')


@section('main')
    <main id="mainContent" class="main-content">
        <!-- Page Container -->
        <div class="page-container ptb-60">
            <div class="container">
                <section class="stores-area stores-area-v2">
                    <h3 class="mb-40 t-uppercase">分类列表</h3>
                    <div class="letters-toolbar p-10 panel mb-40">
                        <span class="all-stores"><a href="#">选择商品</a></span>

                        @foreach ($pinyins as $char)
                            <span>
                                <a class="pinyinBtn" href="javascript:;" data-pinyin="{{ $char }}">{{ $char }}</a>
                            </span>
                        @endforeach
                    </div>
                    <div class="stores-cat panel mb-40">
                        <h3 class="stores-cat-header" id="pinyin_char">随机展示商品</h3>
                        <ul class="row stores-cat-body" id="data">

                            <li class="col-sm-4">
                                <ul>
                                    @foreach ($products[0] ?? [] as $product)
                                        <li><a href="/products/{{ $product->uuid }}"> {{ $product->name }} </a>
                                        </li>
                                    @endforeach
                                </ul>
                            </li>
                            <li class="col-sm-4">
                                <ul>
                                    @foreach ($products[1] ?? [] as $product)
                                        <li><a href="/products/{{ $product->uuid }}"> {{ $product->name }} </a>
                                        </li>
                                    @endforeach
                                </ul>
                            </li>
                            <li class="col-sm-4">
                                <ul>
                                    @foreach ($products[2] ?? [] as $product)
                                        <li><a href="/products/{{ $product->uuid }}"> {{ $product->name }} </a>
                                        </li>
                                    @endforeach
                                </ul>
                            </li>
                        </ul>
                    </div>
                </section>
            </div>
        </div>
        <!-- End Page Container -->


    </main>




@endsection



@section('script')
    <script>
        let url = "/products/pinyin/";
        let loadImg = '<div style="background: #ddd"><img src="/images/loading.svg" style="width: 100%; height: auto;" alt=""></div>';
        let dataContainer = $('#data');

        $('.pinyinBtn').click(function(){
            let pinyin = $(this).data('pinyin');
            let _url = url +  pinyin;
            dataContainer.html(loadImg);

            $.get(_url, function(res){

                let str = '';

                for (let i in res) {
                    let products = res[i];
                    str += '<li class="col-sm-4"><ul>';
                    for (let j in products) {
                        str += "<li><a href="+ url + products[j]['id'] +">"+ products[j]['name'] +"</a></li>";
                    }
                    str += '</ul></li>';
                }

                $('#pinyin_char').text(pinyin);
                dataContainer.html(str);
            });
        });
    </script>
@endsection

resources/views/products/search.blade.php
@extends('layouts.shop')


@section('main')
    <main id="mainContent" class="main-content">
        <div class="page-container ptb-10">
            <div class="container">

                <section class="section deals-area ptb-30">

                    <!-- Page Control -->
                    <header class="page-control panel ptb-15 prl-20 pos-r mb-30">

                        <!-- List Control View -->
                        <ul class="list-control-view list-inline">
                            <li><a href="/categories"><i class="fa fa-reply"></i></a>
                            </li>
                        </ul>
                        <!-- End List Control View -->
                        <div class="right-10 pos-tb-center">
                            <select class="form-control input-sm">
                                <option>排序</option>
                                <option>最新的</option>
                                <option>最受欢迎</option>
                                <option>价格</option>
                            </select>
                        </div>
                    </header>
                    <!-- End Page Control -->
                    <div class="row row-masnory row-tb-20">

                        @forelse($products as $product)
                            <div class="col-xs-12">
                                <div class="deal-single panel">
                                    <div class="row row-rl-0 row-sm-cell">
                                        <div class="col-sm-5">
                                            <a href="/products/{{ $product->uuid }}">
                                                <figure class="deal-thumbnail embed-responsive embed-responsive-16by9 col-absolute-cell" data-bg-img="{{ $product->thumb }}">
                                                    <div class="label-discount left-20 top-15">
                                                        {{ intval(($product->original_price - $product->price)/$product->original_price * 100) }}%
                                                    </div>
                                                    <ul class="deal-actions top-15 right-20">
                                                        <li  class="like-deal" data-id="{{ $product->uuid }}">
                                                            <span>
                                                                <i class="fa fa-heart"></i>
                                                            </span>
                                                        </li>
                                                    </ul>
                                                </figure>
                                            </a>
                                        </div>
                                        <div class="col-sm-7">
                                            <div class="bg-white pt-20 pl-20 pr-15">
                                                <div class="pr-md-10">
                                                    <div class="rating mb-10">
                                                        <div class="mb-10">
                                                            收藏人数 <span class="rating-count rating">{{ $product->users_count }}</span>
                                                        </div>
                                                    </div>
                                                    <h3 class="deal-title mb-10">
                                                        <a href="/products/{{ $product->uuid }}">
                                                            {{ $product->name }}
                                                        </a>
                                                    </h3>
                                                    <p class="text-muted mb-20">
                                                        {!! $product->title !!}
                                                    </p>
                                                </div>
                                                <div class="deal-price pos-r mb-15">
                                                    <h3 class="price ptb-5 text-right">
                                                                <span class="price-sale">
                                                                    {{ $product->original_price }}
                                                                </span>
                                                        ￥ {{ $product->price }}
                                                    </h3>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        @empty
                            <div class="col-xs-12">
                                <div class="deal-single panel">
                                    <div class="row row-rl-0 row-sm-cell">
                                        <div class="col-sm-5">
                                            <a href="#">
                                                <figure class="deal-thumbnail embed-responsive embed-responsive-16by9 col-absolute-cell" data-bg-img="">
                                                    <div class="label-discount left-20 top-15">0</div>
                                                    <ul class="deal-actions top-15 right-20">
                                                        <li  class="like-deal">
                                                            <span>
                                                                <i class="fa fa-heart"></i>
                                                            </span>
                                                        </li>
                                                    </ul>
                                                </figure>
                                            </a>
                                        </div>
                                        <div class="col-sm-7">
                                            <div class="bg-white pt-20 pl-20 pr-15">
                                                <div class="pr-md-10">
                                                    <div class="rating mb-10">

                                                    </div>
                                                    <h3 class="deal-title mb-10">
                                                        <a href="#">
                                                            没有找到你想要的商品
                                                        </a>
                                                    </h3>
                                                    <p class="text-muted mb-20">
                                                        换个关键字再找找吧
                                                    </p>
                                                </div>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        @endforelse
                    </div>

                    <!-- Page Pagination -->
                    <div class="page-pagination text-center mt-30 p-10 panel">
                        <nav>
                            {{ $products->appends(request()->only('keyword'))->links() }}
                        </nav>
                    </div>
                    <!-- End Page Pagination -->

                </section>

            </div>
        </div>


    </main>
@endsection


@section('script')
    <script>
        $('.like-deal').click(function(){
            let id = $(this).data('id');

            alert('收藏商品ID ' + id);

            // 不传递父级点击事件
            return false;
        });

        $('.like-deal').hover(function(){
            $(this).find('i').css('color', 'red');
        }, function(){
            $(this).find('i').css('color', '#fff');
        });
    </script>
@endsection